"use client";
import { useState } from "react";
import Link from "next/link";

const plans = [{ name: "STARTER", price: 2900000, detail: "1 landing page + copy dasar" }, { name: "GROWTH", price: 5900000, detail: "Landing page + copywriting + tracking" }, { name: "SCALE", price: 11900000, detail: "Full funnel + CRO 30 hari" }];
export default function Checkout() {
  const [selected, setSelected] = useState(1);
  const [customer, setCustomer] = useState({ name: "", email: "", whatsapp: "" });
  const plan = plans[selected];
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch("/api/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...customer, plan: plan.name, amount: plan.price }) }); const result = await response.json(); window.location.href = result.checkoutUrl || `/thank-you/?paket=${plan.name}`; };
  return <main className="noise" style={{ minHeight: "100vh", padding: "30px 5vw" }}><Link className="sans" href="/">← Kembali ke FunnelPage</Link><div style={{ maxWidth: 1100, margin: "70px auto", display: "grid", gridTemplateColumns: "1fr 1fr", gap: 70 }}><div><p className="sans" style={{ letterSpacing: 2, fontSize: 11 }}>PILIH PAKET</p><h1 style={{ fontSize: "clamp(3rem,6vw,6rem)", lineHeight: .88 }}>Mulai bangun halaman yang <i>jualan.</i></h1><div style={{ marginTop: 50 }}>{plans.map((item, index) => <button key={item.name} onClick={() => setSelected(index)} style={{ display: "block", width: "100%", textAlign: "left", padding: 22, marginBottom: 10, border: `1px solid ${selected === index ? "var(--ink)" : "var(--line)"}`, background: selected === index ? "var(--acid)" : "transparent", cursor: "pointer" }}><strong className="sans">{item.name}</strong><span className="sans" style={{ float: "right" }}>Rp {item.price.toLocaleString("id-ID")}</span><small className="sans" style={{ display: "block", marginTop: 8 }}>{item.detail}</small></button>)}</div></div><form onSubmit={submit} className="sans" style={{ alignSelf: "end" }}><h2 style={{ fontFamily: "Georgia", fontSize: 30 }}>Data pemesan</h2><label>NAMA<input required value={customer.name} onChange={e => setCustomer({ ...customer, name: e.target.value })} /></label><label>EMAIL<input required type="email" value={customer.email} onChange={e => setCustomer({ ...customer, email: e.target.value })} /></label><label>WHATSAPP<input required value={customer.whatsapp} onChange={e => setCustomer({ ...customer, whatsapp: e.target.value })} /></label><button style={{ width: "100%", padding: 20, border: 0, background: "var(--ink)", color: "var(--acid)", fontWeight: 700, cursor: "pointer" }}>LANJUT KE PEMBAYARAN ↗</button><p style={{ fontSize: 12, color: "var(--muted)", lineHeight: 1.6 }}>Pembayaran diproses melalui Tripay. Setelah pembayaran berhasil, kamu akan diarahkan ke halaman konfirmasi.</p></form></div></main>;
}
