"use client";
import Link from "next/link";
import { useState } from "react";

declare global { interface Window { dataLayer: Array<Record<string, unknown>>; } }

function track(event: string, data: Record<string, string> = {}) { window.dataLayer = window.dataLayer || []; window.dataLayer.push({ event, ...data }); }

export default function Home() {
  const [form, setForm] = useState({ name: "", whatsapp: "", business: "" });
  const submit = async (event: React.FormEvent) => { event.preventDefault(); track("generate_lead", form); await fetch("/api/lead", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); window.location.href = `https://wa.me/${process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || "6281234567890"}?text=${encodeURIComponent(`Halo FunnelPage.id, saya ${form.name} dari ${form.business}. Saya mau audit funnel gratis.`)}`; };
  return <main className="noise">
    <nav className="sans" style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "24px 5vw", borderBottom: "1px solid var(--line)" }}><strong style={{ fontSize: 20 }}>FUNNEL<span style={{ color: "#889d20" }}>PAGE</span><small style={{ fontSize: 10 }}>.ID</small></strong><div style={{ display: "flex", gap: 28, fontSize: 12, letterSpacing: 1 }}><a href="#cara-kerja">CARA KERJA</a><a href="#hasil">HASIL</a><a href="#booking">BOOKING</a></div></nav>
    <section style={{ padding: "10vh 5vw 8vh", maxWidth: 1320, margin: "auto" }}><p className="sans reveal" style={{ letterSpacing: 3, fontSize: 11 }}>LANDING PAGE PERFORMANCE STUDIO / JAKARTA, ID</p><h1 className="display reveal" style={{ fontSize: "10.5vw", lineHeight: .82, letterSpacing: -5, maxWidth: 1100, margin: "32px 0" }}>Klik masuk.<br /><i>Customer</i> keluar.</h1><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 40, alignItems: "end" }}><p className="sans reveal" style={{ maxWidth: 440, lineHeight: 1.7, color: "#5e6259" }}>Kami membangun landing page yang mengubah perhatian dari iklan menjadi aksi nyata: chat, booking, dan transaksi.</p><a className="sans reveal" href="#booking" onClick={() => track("cta_click", { location: "hero" })} style={{ background: "var(--ink)", color: "var(--acid)", padding: "20px 24px", textAlign: "center", fontWeight: 700, maxWidth: 260 }}>MULAI DENGAN AUDIT GRATIS ↗</a></div></section>
    <div className="marquee sans" style={{ padding: "15px 0", fontSize: 12, letterSpacing: 2, background: "var(--acid)" }}><span>STRATEGI • COPYWRITING • DESIGN • DEVELOPMENT • TRACKING • STRATEGI • COPYWRITING • DESIGN • DEVELOPMENT • TRACKING • </span></div>
    <section id="cara-kerja" style={{ padding: "110px 5vw", maxWidth: 1320, margin: "auto" }}><p className="sans" style={{ fontSize: 11, letterSpacing: 2 }}>01 — CARA KERJA</p><h2 style={{ fontSize: "clamp(2.5rem,6vw,6rem)", lineHeight: .9, maxWidth: 850, margin: "30px 0 70px" }}>Setiap elemen punya satu tugas: membuat orang <i>lanjut.</i></h2><div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 1, background: "var(--line)" }}>{["Temukan kebocoran", "Susun pesan yang tepat", "Bangun pengalaman cepat", "Uji sampai menghasilkan"].map((x, i) => <article key={x} style={{ background: "var(--paper)", padding: "25px 18px", minHeight: 190 }}><b className="sans" style={{ color: "#889d20" }}>0{i + 1}</b><h3 style={{ fontSize: 22, marginTop: 55 }}>{x}</h3><p className="sans" style={{ fontSize: 12, lineHeight: 1.5, color: "var(--muted)" }}>Keputusan berbasis data, bukan selera pribadi.</p></article>)}</div></section>
    <section id="hasil" style={{ background: "var(--ink)", color: "var(--paper)", padding: "100px 5vw" }}><div style={{ maxWidth: 1320, margin: "auto" }}><p className="sans" style={{ fontSize: 11, letterSpacing: 2, color: "var(--acid)" }}>02 — HASIL YANG TERUKUR</p><div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 40, marginTop: 70 }}>{[["+143%", "lead berkualitas"], ["2.4x", "lebih banyak booking"], ["0.8s", "target loading"]].map(([n, l]) => <div key={l} style={{ borderTop: "1px solid #555", paddingTop: 20 }}><strong style={{ fontSize: "clamp(3rem,7vw,7rem)", fontWeight: 400 }}>{n}</strong><p className="sans" style={{ color: "#a9ada1", fontSize: 13 }}>{l}</p></div>)}</div></div></section>
    <section id="booking" style={{ padding: "100px 5vw", maxWidth: 1320, margin: "auto", display: "grid", gridTemplateColumns: "1fr 1fr", gap: 80 }}><div><p className="sans" style={{ fontSize: 11, letterSpacing: 2 }}>03 — AUDIT FUNNEL GRATIS</p><h2 style={{ fontSize: "clamp(3rem,6vw,6rem)", lineHeight: .88, margin: "32px 0" }}>Cari tahu apa yang membuat calon customer <i>pergi.</i></h2><p className="sans" style={{ lineHeight: 1.7, color: "var(--muted)" }}>Isi tiga data singkat. Kami kirim observasi awal dan peluang optimasi melalui WhatsApp dalam 24 jam.</p></div><form onSubmit={submit} className="sans" style={{ alignSelf: "end" }}><label>NAMA<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Nama kamu" /></label><label>NAMA BISNIS<input required value={form.business} onChange={e => setForm({ ...form, business: e.target.value })} placeholder="Brand / bisnis" /></label><label>NOMOR WHATSAPP<input required value={form.whatsapp} onChange={e => setForm({ ...form, whatsapp: e.target.value })} placeholder="08xxxxxxxxxx" /></label><button type="submit" style={{ width: "100%", padding: 20, background: "var(--acid)", border: 0, fontWeight: 700, cursor: "pointer" }}>KUNCI SLOT AUDIT ↗</button><small style={{ display: "block", marginTop: 14, color: "var(--muted)" }}>Tanpa kartu kredit. Tanpa komitmen.</small></form></section>
    <section className="sans" style={{ padding: "40px 5vw", borderTop: "1px solid var(--line)", display: "flex", justifyContent: "space-between", gap: 20, flexWrap: "wrap", fontSize: 12 }}><div><strong>FUNNELPAGE.ID</strong><p>Landing page yang bekerja lebih keras.</p></div><div style={{ display: "flex", gap: 20 }}><Link href="/tentang/">Tentang Kami</Link><Link href="/term/">Syarat Ketentuan</Link><Link href="/privacy/">Kebijakan Privasi</Link><Link href="/checkout/">Pilih Paket</Link></div></section>
  </main>;
}
